server.port=8083

spring.application.name=order-service

spring.datasource.url=jdbc:mysql://localhost:3306/order_db
spring.datasource.username=root
spring.datasource.password=Rushi@12345

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Queue config
rabbitmq.queue=order.placed
rabbitmq.exchange=order.exchange
rabbitmq.routing-key=order.routingkey


# Zipkin server URL
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

# Sampling rate — 1.0 means 100% of requests are traced (use 0.1 in production)
management.tracing.sampling.probability=1.0

# Show trace/span IDs in logs
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
